// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_pdf_Stirgamma
double log_pdf_Stirgamma(double x, double a, double b, double m);
RcppExport SEXP _ConjugateDP_log_pdf_Stirgamma(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pdf_Stirgamma(x, a, b, m));
    return rcpp_result_gen;
END_RCPP
}
// rStirgamma_cpp
NumericVector rStirgamma_cpp(int n, double a, double b, double m, double s, double x_star);
RcppExport SEXP _ConjugateDP_rStirgamma_cpp(SEXP nSEXP, SEXP aSEXP, SEXP bSEXP, SEXP mSEXP, SEXP sSEXP, SEXP x_starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x_star(x_starSEXP);
    rcpp_result_gen = Rcpp::wrap(rStirgamma_cpp(n, a, b, m, s, x_star));
    return rcpp_result_gen;
END_RCPP
}
// log_pdf_NCStirgamma
double log_pdf_NCStirgamma(double x, double a, double b, double m, double n, double k);
RcppExport SEXP _ConjugateDP_log_pdf_NCStirgamma(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP mSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pdf_NCStirgamma(x, a, b, m, n, k));
    return rcpp_result_gen;
END_RCPP
}
// rNCStirgamma_cpp
NumericVector rNCStirgamma_cpp(int nsamples, double a, double b, double m, double n, double k, double s, double x_star);
RcppExport SEXP _ConjugateDP_rNCStirgamma_cpp(SEXP nsamplesSEXP, SEXP aSEXP, SEXP bSEXP, SEXP mSEXP, SEXP nSEXP, SEXP kSEXP, SEXP sSEXP, SEXP x_starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x_star(x_starSEXP);
    rcpp_result_gen = Rcpp::wrap(rNCStirgamma_cpp(nsamples, a, b, m, n, k, s, x_star));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ConjugateDP_log_pdf_Stirgamma", (DL_FUNC) &_ConjugateDP_log_pdf_Stirgamma, 4},
    {"_ConjugateDP_rStirgamma_cpp", (DL_FUNC) &_ConjugateDP_rStirgamma_cpp, 6},
    {"_ConjugateDP_log_pdf_NCStirgamma", (DL_FUNC) &_ConjugateDP_log_pdf_NCStirgamma, 6},
    {"_ConjugateDP_rNCStirgamma_cpp", (DL_FUNC) &_ConjugateDP_rNCStirgamma_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_ConjugateDP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
