# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_pdf_A <- function(x, a, b, size) {
    .Call('_ConjugateDP_log_pdf_A', PACKAGE = 'ConjugateDP', x, a, b, size)
}

sampleA_cpp <- function(n, a, b, size, s, x_star) {
    .Call('_ConjugateDP_sampleA_cpp', PACKAGE = 'ConjugateDP', n, a, b, size, s, x_star)
}

