# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_pdf_Stirgamma <- function(x, a, b, m) {
    .Call('_ConjugateDP_log_pdf_Stirgamma', PACKAGE = 'ConjugateDP', x, a, b, m)
}

rStirgamma_cpp <- function(n, a, b, m, s, x_star) {
    .Call('_ConjugateDP_rStirgamma_cpp', PACKAGE = 'ConjugateDP', n, a, b, m, s, x_star)
}

log_pdf_NCStirgamma <- function(x, a, b, m, n, k) {
    .Call('_ConjugateDP_log_pdf_NCStirgamma', PACKAGE = 'ConjugateDP', x, a, b, m, n, k)
}

rNCStirgamma_cpp <- function(nsamples, a, b, m, n, k, s, x_star) {
    .Call('_ConjugateDP_rNCStirgamma_cpp', PACKAGE = 'ConjugateDP', nsamples, a, b, m, n, k, s, x_star)
}

