# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_pdf_Sg <- function(x, a, b, m) {
    .Call('_ConjugateDP_log_pdf_Sg', PACKAGE = 'ConjugateDP', x, a, b, m)
}

rSg_ratio_uniforms <- function(nsamples, a, b, m, Mu, Mv) {
    .Call('_ConjugateDP_rSg_ratio_uniforms', PACKAGE = 'ConjugateDP', nsamples, a, b, m, Mu, Mv)
}

rbeta_cpp <- function(a0, b0) {
    .Call('_ConjugateDP_rbeta_cpp', PACKAGE = 'ConjugateDP', a0, b0)
}

rSg_beta_prime <- function(nsamples, a, b, m) {
    .Call('_ConjugateDP_rSg_beta_prime', PACKAGE = 'ConjugateDP', nsamples, a, b, m)
}

